# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\Logiciels\Logiciels_techniques_labo\0_ A valider tester\Declaration incertitudes\0.1\GUI\Main_Declaration_Incertitudes.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainDeclaration_Incertitudes(object):
    def setupUi(self, MainDeclaration_Incertitudes):
        MainDeclaration_Incertitudes.setObjectName(_fromUtf8("MainDeclaration_Incertitudes"))
        MainDeclaration_Incertitudes.resize(1370, 1093)
        self.centralWidget = QtGui.QWidget(MainDeclaration_Incertitudes)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1350, 1052))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8("QTabBar::tab {\n"
"   font-size: 12px;\n"
"font-weight: bold;\n"
"min-width: 50ex;\n"
" padding: 3px\n"
"\n"
"}"))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Recapitulatif = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Recapitulatif.setFont(font)
        self.Recapitulatif.setObjectName(_fromUtf8("Recapitulatif"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Recapitulatif)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.Recapitulatif)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("QLabel{\n"
"background-color: rgb(170, 255, 255);\n"
"border: 1px solid Black;\n"
"border-radius: 5px;}"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.tableWidget = QtGui.QTableWidget(self.Recapitulatif)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableWidget.setWhatsThis(_fromUtf8(""))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.Recapitulatif, _fromUtf8(""))
        self.Saisie = QtGui.QWidget()
        self.Saisie.setObjectName(_fromUtf8("Saisie"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Saisie)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_10 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_id_decla = QtGui.QLineEdit(self.Saisie)
        self.lineEdit_id_decla.setReadOnly(True)
        self.lineEdit_id_decla.setObjectName(_fromUtf8("lineEdit_id_decla"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_id_decla)
        self.verticalLayout_5.addLayout(self.formLayout_4)
        self.dateEdit = QtGui.QDateEdit(self.Saisie)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.verticalLayout_5.addWidget(self.dateEdit)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.comboBox_type_declaration = QtGui.QComboBox(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_type_declaration.setFont(font)
        self.comboBox_type_declaration.setObjectName(_fromUtf8("comboBox_type_declaration"))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.comboBox_type_declaration.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_type_declaration)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.pushButton_select_etalons = QtGui.QPushButton(self.Saisie)
        self.pushButton_select_etalons.setObjectName(_fromUtf8("pushButton_select_etalons"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_select_etalons)
        self.label_4 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.pushButton_select_CE = QtGui.QPushButton(self.Saisie)
        self.pushButton_select_CE.setObjectName(_fromUtf8("pushButton_select_CE"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButton_select_CE)
        self.tableWidget_recap_select_etalons = QtGui.QTableWidget(self.Saisie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_recap_select_etalons.sizePolicy().hasHeightForWidth())
        self.tableWidget_recap_select_etalons.setSizePolicy(sizePolicy)
        self.tableWidget_recap_select_etalons.setObjectName(_fromUtf8("tableWidget_recap_select_etalons"))
        self.tableWidget_recap_select_etalons.setColumnCount(3)
        self.tableWidget_recap_select_etalons.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_select_etalons.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_select_etalons.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_select_etalons.setHorizontalHeaderItem(2, item)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.tableWidget_recap_select_etalons)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_6 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.pushButton_select_generateurs = QtGui.QPushButton(self.Saisie)
        self.pushButton_select_generateurs.setObjectName(_fromUtf8("pushButton_select_generateurs"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_select_generateurs)
        self.label_8 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.pushButton_select_caract = QtGui.QPushButton(self.Saisie)
        self.pushButton_select_caract.setObjectName(_fromUtf8("pushButton_select_caract"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButton_select_caract)
        self.tableWidget_recap_caracterisation = QtGui.QTableWidget(self.Saisie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_recap_caracterisation.sizePolicy().hasHeightForWidth())
        self.tableWidget_recap_caracterisation.setSizePolicy(sizePolicy)
        self.tableWidget_recap_caracterisation.setObjectName(_fromUtf8("tableWidget_recap_caracterisation"))
        self.tableWidget_recap_caracterisation.setColumnCount(3)
        self.tableWidget_recap_caracterisation.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_caracterisation.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_caracterisation.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap_caracterisation.setHorizontalHeaderItem(2, item)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.tableWidget_recap_caracterisation)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.label_9 = QtGui.QLabel(self.Saisie)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.splitter = QtGui.QSplitter(self.Saisie)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.textEdit_commentaire = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_commentaire.sizePolicy().hasHeightForWidth())
        self.textEdit_commentaire.setSizePolicy(sizePolicy)
        self.textEdit_commentaire.setAutoFormatting(QtGui.QTextEdit.AutoBulletList)
        self.textEdit_commentaire.setTabStopWidth(80)
        self.textEdit_commentaire.setObjectName(_fromUtf8("textEdit_commentaire"))
        self.tableWidget_incertitudes = QtGui.QTableWidget(self.splitter)
        self.tableWidget_incertitudes.setObjectName(_fromUtf8("tableWidget_incertitudes"))
        self.tableWidget_incertitudes.setColumnCount(4)
        self.tableWidget_incertitudes.setRowCount(13)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_incertitudes.setItem(12, 1, item)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit_u2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_u2.setObjectName(_fromUtf8("lineEdit_u2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_u2)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_u = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_u.setObjectName(_fromUtf8("lineEdit_u"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_u)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_U = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_U.setObjectName(_fromUtf8("lineEdit_U"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_U)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_u2_client = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_u2_client.setObjectName(_fromUtf8("lineEdit_u2_client"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_u2_client)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_u_client = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_u_client.setObjectName(_fromUtf8("lineEdit_u_client"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_u_client)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_U_client = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_U_client.setObjectName(_fromUtf8("lineEdit_U_client"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_U_client)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.verticalLayout_5.addWidget(self.splitter)
        self.tabWidget.addTab(self.Saisie, _fromUtf8(""))
        self.Graphique = QtGui.QWidget()
        self.Graphique.setObjectName(_fromUtf8("Graphique"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Graphique)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.graphique = matplotlibWidget(self.Graphique)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphique.sizePolicy().hasHeightForWidth())
        self.graphique.setSizePolicy(sizePolicy)
        self.graphique.setObjectName(_fromUtf8("graphique"))
        self.verticalLayout_2.addWidget(self.graphique)
        self.tabWidget.addTab(self.Graphique, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        MainDeclaration_Incertitudes.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainDeclaration_Incertitudes)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1370, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuRapport = QtGui.QMenu(self.menuBar)
        self.menuRapport.setObjectName(_fromUtf8("menuRapport"))
        self.menuSauvegarde = QtGui.QMenu(self.menuBar)
        self.menuSauvegarde.setObjectName(_fromUtf8("menuSauvegarde"))
        MainDeclaration_Incertitudes.setMenuBar(self.menuBar)
        self.actionNouvelle_caracterisation_enceinte = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionNouvelle_caracterisation_enceinte.setObjectName(_fromUtf8("actionNouvelle_caracterisation_enceinte"))
        self.actionModifier_caracterisation_enceinte = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionModifier_caracterisation_enceinte.setObjectName(_fromUtf8("actionModifier_caracterisation_enceinte"))
        self.actionVisualiser_caracterisation_enceinte = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionVisualiser_caracterisation_enceinte.setObjectName(_fromUtf8("actionVisualiser_caracterisation_enceinte"))
        self.actionNouvelle_caracterisation_bain = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionNouvelle_caracterisation_bain.setObjectName(_fromUtf8("actionNouvelle_caracterisation_bain"))
        self.actionVisualiser_caracterisation_bain = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionVisualiser_caracterisation_bain.setObjectName(_fromUtf8("actionVisualiser_caracterisation_bain"))
        self.actionModifier_caracterisation_bain = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionModifier_caracterisation_bain.setObjectName(_fromUtf8("actionModifier_caracterisation_bain"))
        self.actionNouvelle_caracterisation_four = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionNouvelle_caracterisation_four.setObjectName(_fromUtf8("actionNouvelle_caracterisation_four"))
        self.actionModifier_caracterisation_four = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionModifier_caracterisation_four.setObjectName(_fromUtf8("actionModifier_caracterisation_four"))
        self.actionVisualiser_caracterisation_four = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionVisualiser_caracterisation_four.setObjectName(_fromUtf8("actionVisualiser_caracterisation_four"))
        self.actionEditer_une_rapport = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionEditer_une_rapport.setObjectName(_fromUtf8("actionEditer_une_rapport"))
        self.actionEnregistrement = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionEnregistrement.setObjectName(_fromUtf8("actionEnregistrement"))
        self.actionMise_jour = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionMise_jour.setObjectName(_fromUtf8("actionMise_jour"))
        self.actionArchivage = QtGui.QAction(MainDeclaration_Incertitudes)
        self.actionArchivage.setObjectName(_fromUtf8("actionArchivage"))
        self.menuRapport.addAction(self.actionEditer_une_rapport)
        self.menuSauvegarde.addAction(self.actionEnregistrement)
        self.menuSauvegarde.addAction(self.actionMise_jour)
        self.menuSauvegarde.addAction(self.actionArchivage)
        self.menuBar.addAction(self.menuRapport.menuAction())
        self.menuBar.addAction(self.menuSauvegarde.menuAction())

        self.retranslateUi(MainDeclaration_Incertitudes)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainDeclaration_Incertitudes)

    def retranslateUi(self, MainDeclaration_Incertitudes):
        MainDeclaration_Incertitudes.setWindowTitle(_translate("MainDeclaration_Incertitudes", "Declaration_Incertitudes", None))
        self.tabWidget.setWhatsThis(_translate("MainDeclaration_Incertitudes", "<html><head/><body><p>t\'(t(t\'\'(t(\'</p></body></html>", None))
        self.label_7.setText(_translate("MainDeclaration_Incertitudes", "Recapitulatif des Declarations", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDeclaration_Incertitudes", "ID_Declaration", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDeclaration_Incertitudes", "Date", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDeclaration_Incertitudes", "Type de Declaration", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDeclaration_Incertitudes", "Archivage", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDeclaration_Incertitudes", "Commentaire", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainDeclaration_Incertitudes", "u_final k=1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Recapitulatif), _translate("MainDeclaration_Incertitudes", "Menu Principal", None))
        self.label_10.setText(_translate("MainDeclaration_Incertitudes", "ID Declaration", None))
        self.comboBox_type_declaration.setItemText(0, _translate("MainDeclaration_Incertitudes", "*", None))
        self.comboBox_type_declaration.setItemText(1, _translate("MainDeclaration_Incertitudes", "MEILLEURES_LIQUIDE", None))
        self.comboBox_type_declaration.setItemText(2, _translate("MainDeclaration_Incertitudes", "MEILLEURES_BGF", None))
        self.comboBox_type_declaration.setItemText(3, _translate("MainDeclaration_Incertitudes", "COURANTES_LIQUIDE", None))
        self.comboBox_type_declaration.setItemText(4, _translate("MainDeclaration_Incertitudes", "COURANTES_BGF", None))
        self.comboBox_type_declaration.setItemText(5, _translate("MainDeclaration_Incertitudes", "COURANTES_AIR", None))
        self.comboBox_type_declaration.setItemText(6, _translate("MainDeclaration_Incertitudes", "COURANTES_SITE", None))
        self.label_5.setText(_translate("MainDeclaration_Incertitudes", "Selection Etalon(s)", None))
        self.pushButton_select_etalons.setText(_translate("MainDeclaration_Incertitudes", "PushButton", None))
        self.label_4.setText(_translate("MainDeclaration_Incertitudes", "Selection CE", None))
        self.pushButton_select_CE.setText(_translate("MainDeclaration_Incertitudes", "PushButton", None))
        item = self.tableWidget_recap_select_etalons.horizontalHeaderItem(0)
        item.setText(_translate("MainDeclaration_Incertitudes", "Date", None))
        item = self.tableWidget_recap_select_etalons.horizontalHeaderItem(1)
        item.setText(_translate("MainDeclaration_Incertitudes", "N°Certificat", None))
        item = self.tableWidget_recap_select_etalons.horizontalHeaderItem(2)
        item.setText(_translate("MainDeclaration_Incertitudes", "Nom_Etalon", None))
        self.label_6.setText(_translate("MainDeclaration_Incertitudes", "Generateur(s)", None))
        self.pushButton_select_generateurs.setText(_translate("MainDeclaration_Incertitudes", "PushButton", None))
        self.label_8.setText(_translate("MainDeclaration_Incertitudes", "Caracterisation", None))
        self.pushButton_select_caract.setText(_translate("MainDeclaration_Incertitudes", "PushButton", None))
        item = self.tableWidget_recap_caracterisation.horizontalHeaderItem(0)
        item.setText(_translate("MainDeclaration_Incertitudes", "Date", None))
        item = self.tableWidget_recap_caracterisation.horizontalHeaderItem(1)
        item.setText(_translate("MainDeclaration_Incertitudes", "ID_Caracterisation", None))
        item = self.tableWidget_recap_caracterisation.horizontalHeaderItem(2)
        item.setText(_translate("MainDeclaration_Incertitudes", "Nom_Generateur", None))
        self.label_9.setText(_translate("MainDeclaration_Incertitudes", "Commentaires :", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(0)
        item.setText(_translate("MainDeclaration_Incertitudes", "Etalonnage_Etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(1)
        item.setText(_translate("MainDeclaration_Incertitudes", "Erreur_Modelisation_Etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(2)
        item.setText(_translate("MainDeclaration_Incertitudes", "Resolution_Etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(3)
        item.setText(_translate("MainDeclaration_Incertitudes", "Derive_etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(4)
        item.setText(_translate("MainDeclaration_Incertitudes", "Fuite_Thermique_Etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(5)
        item.setText(_translate("MainDeclaration_Incertitudes", "Autoechauffement", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(6)
        item.setText(_translate("MainDeclaration_Incertitudes", "Temp_Ambiante_Etalon", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(7)
        item.setText(_translate("MainDeclaration_Incertitudes", "Stabilite_Generateur", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(8)
        item.setText(_translate("MainDeclaration_Incertitudes", "Homogeneite_generateur", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(9)
        item.setText(_translate("MainDeclaration_Incertitudes", "Moyens de caracterisation", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(10)
        item.setText(_translate("MainDeclaration_Incertitudes", "Rayonnement", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(11)
        item.setText(_translate("MainDeclaration_Incertitudes", "Resolution_Chaine_Cliente", None))
        item = self.tableWidget_incertitudes.verticalHeaderItem(12)
        item.setText(_translate("MainDeclaration_Incertitudes", "Fuite_Thermique_Chaine_Cliente", None))
        item = self.tableWidget_incertitudes.horizontalHeaderItem(0)
        item.setText(_translate("MainDeclaration_Incertitudes", "Valeur", None))
        item = self.tableWidget_incertitudes.horizontalHeaderItem(1)
        item.setText(_translate("MainDeclaration_Incertitudes", "Coefficient diviseur", None))
        item = self.tableWidget_incertitudes.horizontalHeaderItem(2)
        item.setText(_translate("MainDeclaration_Incertitudes", "u (k = 1)", None))
        item = self.tableWidget_incertitudes.horizontalHeaderItem(3)
        item.setText(_translate("MainDeclaration_Incertitudes", "u²", None))
        __sortingEnabled = self.tableWidget_incertitudes.isSortingEnabled()
        self.tableWidget_incertitudes.setSortingEnabled(False)
        item = self.tableWidget_incertitudes.item(0, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "2", None))
        item = self.tableWidget_incertitudes.item(1, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(2, 0)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.001", None))
        item = self.tableWidget_incertitudes.item(2, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "2*√3", None))
        item = self.tableWidget_incertitudes.item(2, 2)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.000288675135", None))
        item = self.tableWidget_incertitudes.item(2, 3)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.000000083333333567268225", None))
        item = self.tableWidget_incertitudes.item(3, 0)
        item.setText(_translate("MainDeclaration_Incertitudes", "0", None))
        item = self.tableWidget_incertitudes.item(3, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(3, 2)
        item.setText(_translate("MainDeclaration_Incertitudes", "0", None))
        item = self.tableWidget_incertitudes.item(3, 3)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.000225333333332", None))
        item = self.tableWidget_incertitudes.item(4, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(5, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(6, 0)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.006", None))
        item = self.tableWidget_incertitudes.item(6, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "2*√3", None))
        item = self.tableWidget_incertitudes.item(6, 2)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.001732050808", None))
        item = self.tableWidget_incertitudes.item(6, 3)
        item.setText(_translate("MainDeclaration_Incertitudes", "0.000003000000001493452864", None))
        item = self.tableWidget_incertitudes.item(7, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "2*√3", None))
        item = self.tableWidget_incertitudes.item(8, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(9, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "/", None))
        item = self.tableWidget_incertitudes.item(10, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        item = self.tableWidget_incertitudes.item(11, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "2*√3", None))
        item = self.tableWidget_incertitudes.item(12, 1)
        item.setText(_translate("MainDeclaration_Incertitudes", "√3", None))
        self.tableWidget_incertitudes.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainDeclaration_Incertitudes", "Somme u² ", None))
        self.label_2.setText(_translate("MainDeclaration_Incertitudes", "u final", None))
        self.label_3.setText(_translate("MainDeclaration_Incertitudes", "U final( k=2 )", None))
        self.label_11.setText(_translate("MainDeclaration_Incertitudes", "Etalon et Generateur :", None))
        self.label_12.setText(_translate("MainDeclaration_Incertitudes", "Somme u² ", None))
        self.label_13.setText(_translate("MainDeclaration_Incertitudes", "u declaration", None))
        self.label_14.setText(_translate("MainDeclaration_Incertitudes", "U declaration( k=2 )", None))
        self.label_15.setText(_translate("MainDeclaration_Incertitudes", "Total", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Saisie), _translate("MainDeclaration_Incertitudes", "Données / Saisie", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Graphique), _translate("MainDeclaration_Incertitudes", "Graphique", None))
        self.menuRapport.setTitle(_translate("MainDeclaration_Incertitudes", "Rapport", None))
        self.menuSauvegarde.setTitle(_translate("MainDeclaration_Incertitudes", "Sauvegarde", None))
        self.actionNouvelle_caracterisation_enceinte.setText(_translate("MainDeclaration_Incertitudes", "Nouvelle caracterisation", None))
        self.actionModifier_caracterisation_enceinte.setText(_translate("MainDeclaration_Incertitudes", "Modifier caracterisation", None))
        self.actionVisualiser_caracterisation_enceinte.setText(_translate("MainDeclaration_Incertitudes", "Visualiser caracterisation", None))
        self.actionNouvelle_caracterisation_bain.setText(_translate("MainDeclaration_Incertitudes", "Nouvelle caracterisation", None))
        self.actionVisualiser_caracterisation_bain.setText(_translate("MainDeclaration_Incertitudes", "Visualiser caracterisation", None))
        self.actionModifier_caracterisation_bain.setText(_translate("MainDeclaration_Incertitudes", "Modifier caracterisation", None))
        self.actionNouvelle_caracterisation_four.setText(_translate("MainDeclaration_Incertitudes", "Nouvelle caracterisation", None))
        self.actionModifier_caracterisation_four.setText(_translate("MainDeclaration_Incertitudes", "Modifier caracterisation", None))
        self.actionVisualiser_caracterisation_four.setText(_translate("MainDeclaration_Incertitudes", "Visualiser caracterisation", None))
        self.actionEditer_une_rapport.setText(_translate("MainDeclaration_Incertitudes", "Editer une rapport", None))
        self.actionEnregistrement.setText(_translate("MainDeclaration_Incertitudes", "Enregistrement", None))
        self.actionMise_jour.setText(_translate("MainDeclaration_Incertitudes", "Mise à jour", None))
        self.actionArchivage.setText(_translate("MainDeclaration_Incertitudes", "Archivage", None))

from Modules.Declaration_incertitudes.GUI.matplotlibwidgetFile import matplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainDeclaration_Incertitudes = QtGui.QMainWindow()
    ui = Ui_MainDeclaration_Incertitudes()
    ui.setupUi(MainDeclaration_Incertitudes)
    MainDeclaration_Incertitudes.show()
    sys.exit(app.exec_())

