# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Travail\EFS\Travail accreditation\SQ\Developpement Informatique\Afficheurs\Afficheur-V0.2\GUI\creation_afficheur.ui'
#
# Created: Fri Mar 20 14:20:20 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Creation_afficheur(object):
    def setupUi(self, Creation_afficheur):
        Creation_afficheur.setObjectName(_fromUtf8("Creation_afficheur"))
        Creation_afficheur.setWindowModality(QtCore.Qt.WindowModal)
        Creation_afficheur.resize(642, 487)
        Creation_afficheur.setSizeGripEnabled(True)
        Creation_afficheur.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Creation_afficheur)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_automatique = QtGui.QRadioButton(self.groupBox)
        self.radioButton_automatique.setChecked(True)
        self.radioButton_automatique.setObjectName(_fromUtf8("radioButton_automatique"))
        self.gridLayout_2.addWidget(self.radioButton_automatique, 0, 0, 1, 1)
        self.radioButton_manuelle = QtGui.QRadioButton(self.groupBox)
        self.radioButton_manuelle.setObjectName(_fromUtf8("radioButton_manuelle"))
        self.gridLayout_2.addWidget(self.radioButton_manuelle, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_13 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_identification = QtGui.QLineEdit(Creation_afficheur)
        self.lineEdit_identification.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_identification.sizePolicy().hasHeightForWidth())
        self.lineEdit_identification.setSizePolicy(sizePolicy)
        self.lineEdit_identification.setObjectName(_fromUtf8("lineEdit_identification"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_identification)
        self.label = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox_code_client = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_code_client.sizePolicy().hasHeightForWidth())
        self.comboBox_code_client.setSizePolicy(sizePolicy)
        self.comboBox_code_client.setObjectName(_fromUtf8("comboBox_code_client"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_code_client)
        self.label_2 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_domaine_mesure = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_domaine_mesure.sizePolicy().hasHeightForWidth())
        self.comboBox_domaine_mesure.setSizePolicy(sizePolicy)
        self.comboBox_domaine_mesure.setObjectName(_fromUtf8("comboBox_domaine_mesure"))
        self.comboBox_domaine_mesure.addItem(_fromUtf8(""))
        self.comboBox_domaine_mesure.addItem(_fromUtf8(""))
        self.comboBox_domaine_mesure.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_domaine_mesure)
        self.label_3 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox_famille = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_famille.sizePolicy().hasHeightForWidth())
        self.comboBox_famille.setSizePolicy(sizePolicy)
        self.comboBox_famille.setObjectName(_fromUtf8("comboBox_famille"))
        self.comboBox_famille.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_famille)
        self.label_4 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox_designation = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_designation.sizePolicy().hasHeightForWidth())
        self.comboBox_designation.setSizePolicy(sizePolicy)
        self.comboBox_designation.setObjectName(_fromUtf8("comboBox_designation"))
        self.comboBox_designation.addItem(_fromUtf8(""))
        self.comboBox_designation.addItem(_fromUtf8(""))
        self.comboBox_designation.addItem(_fromUtf8(""))
        self.comboBox_designation.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_designation)
        self.label_5 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBox_type = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_type.sizePolicy().hasHeightForWidth())
        self.comboBox_type.setSizePolicy(sizePolicy)
        self.comboBox_type.setEditable(True)
        self.comboBox_type.setObjectName(_fromUtf8("comboBox_type"))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.comboBox_type.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_type)
        self.label_6 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.comboBox_designation_litterale = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_designation_litterale.sizePolicy().hasHeightForWidth())
        self.comboBox_designation_litterale.setSizePolicy(sizePolicy)
        self.comboBox_designation_litterale.setEditable(True)
        self.comboBox_designation_litterale.setObjectName(_fromUtf8("comboBox_designation_litterale"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBox_designation_litterale)
        self.label_7 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_7)
        self.comboBox_constructeur = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_constructeur.sizePolicy().hasHeightForWidth())
        self.comboBox_constructeur.setSizePolicy(sizePolicy)
        self.comboBox_constructeur.setEditable(True)
        self.comboBox_constructeur.setObjectName(_fromUtf8("comboBox_constructeur"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.comboBox_constructeur)
        self.label_8 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.comboBox_ref_constructeur = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_ref_constructeur.sizePolicy().hasHeightForWidth())
        self.comboBox_ref_constructeur.setSizePolicy(sizePolicy)
        self.comboBox_ref_constructeur.setEditable(True)
        self.comboBox_ref_constructeur.setObjectName(_fromUtf8("comboBox_ref_constructeur"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.comboBox_ref_constructeur)
        self.label_10 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_resolution = QtGui.QLineEdit(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_resolution.sizePolicy().hasHeightForWidth())
        self.lineEdit_resolution.setSizePolicy(sizePolicy)
        self.lineEdit_resolution.setObjectName(_fromUtf8("lineEdit_resolution"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_resolution)
        self.label_11 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.comboBox_affectation = QtGui.QComboBox(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_affectation.sizePolicy().hasHeightForWidth())
        self.comboBox_affectation.setSizePolicy(sizePolicy)
        self.comboBox_affectation.setEditable(True)
        self.comboBox_affectation.setObjectName(_fromUtf8("comboBox_affectation"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.comboBox_affectation)
        self.label_12 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_nserie = QtGui.QLineEdit(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_nserie.sizePolicy().hasHeightForWidth())
        self.lineEdit_nserie.setSizePolicy(sizePolicy)
        self.lineEdit_nserie.setObjectName(_fromUtf8("lineEdit_nserie"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit_nserie)
        self.label_14 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_nsap = QtGui.QLineEdit(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit_nsap.sizePolicy().hasHeightForWidth())
        self.lineEdit_nsap.setSizePolicy(sizePolicy)
        self.lineEdit_nsap.setObjectName(_fromUtf8("lineEdit_nsap"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit_nsap)
        self.label_15 = QtGui.QLabel(Creation_afficheur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_15)
        self.textEdit_sous_affectation = QtGui.QTextEdit(Creation_afficheur)
        self.textEdit_sous_affectation.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_sous_affectation.setObjectName(_fromUtf8("textEdit_sous_affectation"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.textEdit_sous_affectation)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(Creation_afficheur)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Creation_afficheur)
        self.comboBox_designation_litterale.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Creation_afficheur)

    def retranslateUi(self, Creation_afficheur):
        Creation_afficheur.setWindowTitle(_translate("Creation_afficheur", "Création d\'afficheur", None))
        self.groupBox.setTitle(_translate("Creation_afficheur", "Identification", None))
        self.radioButton_automatique.setText(_translate("Creation_afficheur", "Automatique", None))
        self.radioButton_manuelle.setText(_translate("Creation_afficheur", "Manuelle", None))
        self.label_13.setText(_translate("Creation_afficheur", "Identification", None))
        self.label.setText(_translate("Creation_afficheur", "Code client", None))
        self.label_2.setText(_translate("Creation_afficheur", "Domaine de mesure", None))
        self.comboBox_domaine_mesure.setItemText(0, _translate("Creation_afficheur", "Température", None))
        self.comboBox_domaine_mesure.setItemText(1, _translate("Creation_afficheur", "Temps-Fréquence", None))
        self.comboBox_domaine_mesure.setItemText(2, _translate("Creation_afficheur", "Vitesse", None))
        self.label_3.setText(_translate("Creation_afficheur", "Famille", None))
        self.comboBox_famille.setItemText(0, _translate("Creation_afficheur", "Variable", None))
        self.label_4.setText(_translate("Creation_afficheur", "Désignation", None))
        self.comboBox_designation.setItemText(0, _translate("Creation_afficheur", "Sonde alarme température", None))
        self.comboBox_designation.setItemText(1, _translate("Creation_afficheur", "Afficheur de température", None))
        self.comboBox_designation.setItemText(2, _translate("Creation_afficheur", "Afficheur de temps", None))
        self.comboBox_designation.setItemText(3, _translate("Creation_afficheur", "Afficheur de vitesse", None))
        self.label_5.setText(_translate("Creation_afficheur", "Type", None))
        self.comboBox_type.setItemText(0, _translate("Creation_afficheur", "/", None))
        self.comboBox_type.setItemText(1, _translate("Creation_afficheur", "Thermistance", None))
        self.comboBox_type.setItemText(2, _translate("Creation_afficheur", "PT100", None))
        self.comboBox_type.setItemText(3, _translate("Creation_afficheur", "PT1000", None))
        self.label_6.setText(_translate("Creation_afficheur", "Désignation litterale", None))
        self.label_7.setText(_translate("Creation_afficheur", "Constructeur", None))
        self.label_8.setText(_translate("Creation_afficheur", "Reference constructeur", None))
        self.label_10.setText(_translate("Creation_afficheur", "Résolution", None))
        self.label_11.setText(_translate("Creation_afficheur", "Affectation", None))
        self.label_12.setText(_translate("Creation_afficheur", "N_serie", None))
        self.label_14.setText(_translate("Creation_afficheur", "N_SAP", None))
        self.label_15.setText(_translate("Creation_afficheur", "Sous affectation/ \n"
" Renseignement complementaire", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Creation_afficheur = QtGui.QDialog()
    ui = Ui_Creation_afficheur()
    ui.setupUi(Creation_afficheur)
    Creation_afficheur.show()
    sys.exit(app.exec_())

