# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Developpement Informatique\Python\Administration\GUI\Main_Administration.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(982, 809)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dateEdit = QtGui.QDateEdit(self.centralWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.verticalLayout.addWidget(self.dateEdit)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.lineEdit_valeur = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_valeur.sizePolicy().hasHeightForWidth())
        self.lineEdit_valeur.setSizePolicy(sizePolicy)
        self.lineEdit_valeur.setObjectName(_fromUtf8("lineEdit_valeur"))
        self.verticalLayout_5.addWidget(self.lineEdit_valeur)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.comboBox_signe = QtGui.QComboBox(self.groupBox)
        self.comboBox_signe.setObjectName(_fromUtf8("comboBox_signe"))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.comboBox_signe.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.comboBox_signe)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.comboBox_nom_colonne = QtGui.QComboBox(self.groupBox)
        self.comboBox_nom_colonne.setObjectName(_fromUtf8("comboBox_nom_colonne"))
        self.verticalLayout_4.addWidget(self.comboBox_nom_colonne)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableView_instruments = Tableview_donnees_fichier(self.splitter)
        self.tableView_instruments.setObjectName(_fromUtf8("tableView_instruments"))
        self.graph_instruments = QtGui.QWidget(self.splitter)
        self.graph_instruments.setObjectName(_fromUtf8("graph_instruments"))
        self.verticalLayout_7.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tableView_reception = Tableview_donnees_fichier(self.splitter_2)
        self.tableView_reception.setObjectName(_fromUtf8("tableView_reception"))
        self.graph_reception = QtGui.QWidget(self.splitter_2)
        self.graph_reception.setObjectName(_fromUtf8("graph_reception"))
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuTemperature = QtGui.QMenu(self.menuBar)
        self.menuTemperature.setObjectName(_fromUtf8("menuTemperature"))
        self.menuAfficheurs = QtGui.QMenu(self.menuBar)
        self.menuAfficheurs.setObjectName(_fromUtf8("menuAfficheurs"))
        self.menuAdministration = QtGui.QMenu(self.menuBar)
        self.menuAdministration.setObjectName(_fromUtf8("menuAdministration"))
        self.menuInstruments = QtGui.QMenu(self.menuAdministration)
        self.menuInstruments.setObjectName(_fromUtf8("menuInstruments"))
        self.menuIntervention = QtGui.QMenu(self.menuInstruments)
        self.menuIntervention.setObjectName(_fromUtf8("menuIntervention"))
        self.menuClients = QtGui.QMenu(self.menuAdministration)
        self.menuClients.setObjectName(_fromUtf8("menuClients"))
        self.menuModification = QtGui.QMenu(self.menuClients)
        self.menuModification.setObjectName(_fromUtf8("menuModification"))
        self.menuInterventions = QtGui.QMenu(self.menuAdministration)
        self.menuInterventions.setObjectName(_fromUtf8("menuInterventions"))
        self.menuBase_de_Donnees = QtGui.QMenu(self.menuAdministration)
        self.menuBase_de_Donnees.setObjectName(_fromUtf8("menuBase_de_Donnees"))
        self.menuExploitation_Certificats = QtGui.QMenu(self.menuBar)
        self.menuExploitation_Certificats.setObjectName(_fromUtf8("menuExploitation_Certificats"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionLaboTemp = QtGui.QAction(MainWindow)
        self.actionLaboTemp.setObjectName(_fromUtf8("actionLaboTemp"))
        self.actionSynchronisation_enregisteurs = QtGui.QAction(MainWindow)
        self.actionSynchronisation_enregisteurs.setObjectName(_fromUtf8("actionSynchronisation_enregisteurs"))
        self.actionCaracterisation_Generateurs = QtGui.QAction(MainWindow)
        self.actionCaracterisation_Generateurs.setObjectName(_fromUtf8("actionCaracterisation_Generateurs"))
        self.actionAfficheurs = QtGui.QAction(MainWindow)
        self.actionAfficheurs.setObjectName(_fromUtf8("actionAfficheurs"))
        self.actionIndicateurs = QtGui.QAction(MainWindow)
        self.actionIndicateurs.setObjectName(_fromUtf8("actionIndicateurs"))
        self.actionCreation = QtGui.QAction(MainWindow)
        self.actionCreation.setObjectName(_fromUtf8("actionCreation"))
        self.actionModification = QtGui.QAction(MainWindow)
        self.actionModification.setObjectName(_fromUtf8("actionModification"))
        self.actionRecherche = QtGui.QAction(MainWindow)
        self.actionRecherche.setObjectName(_fromUtf8("actionRecherche"))
        self.actionCreation_2 = QtGui.QAction(MainWindow)
        self.actionCreation_2.setObjectName(_fromUtf8("actionCreation_2"))
        self.actionRecherche_2 = QtGui.QAction(MainWindow)
        self.actionRecherche_2.setObjectName(_fromUtf8("actionRecherche_2"))
        self.actionCreer = QtGui.QAction(MainWindow)
        self.actionCreer.setObjectName(_fromUtf8("actionCreer"))
        self.actionModifier = QtGui.QAction(MainWindow)
        self.actionModifier.setObjectName(_fromUtf8("actionModifier"))
        self.actionAffecter = QtGui.QAction(MainWindow)
        self.actionAffecter.setObjectName(_fromUtf8("actionAffecter"))
        self.actionModifier_2 = QtGui.QAction(MainWindow)
        self.actionModifier_2.setObjectName(_fromUtf8("actionModifier_2"))
        self.actionRechercher = QtGui.QAction(MainWindow)
        self.actionRechercher.setObjectName(_fromUtf8("actionRechercher"))
        self.actionPolynome = QtGui.QAction(MainWindow)
        self.actionPolynome.setObjectName(_fromUtf8("actionPolynome"))
        self.actionConsultation = QtGui.QAction(MainWindow)
        self.actionConsultation.setObjectName(_fromUtf8("actionConsultation"))
        self.actionPilotage_des_instruments = QtGui.QAction(MainWindow)
        self.actionPilotage_des_instruments.setObjectName(_fromUtf8("actionPilotage_des_instruments"))
        self.actionDeclaration_incertitudes = QtGui.QAction(MainWindow)
        self.actionDeclaration_incertitudes.setObjectName(_fromUtf8("actionDeclaration_incertitudes"))
        self.actionEntite_Client = QtGui.QAction(MainWindow)
        self.actionEntite_Client.setObjectName(_fromUtf8("actionEntite_Client"))
        self.actionSite_Client = QtGui.QAction(MainWindow)
        self.actionSite_Client.setObjectName(_fromUtf8("actionSite_Client"))
        self.actionServices_Client = QtGui.QAction(MainWindow)
        self.actionServices_Client.setObjectName(_fromUtf8("actionServices_Client"))
        self.actionCartographie = QtGui.QAction(MainWindow)
        self.actionCartographie.setObjectName(_fromUtf8("actionCartographie"))
        self.actionReception_Expedition = QtGui.QAction(MainWindow)
        self.actionReception_Expedition.setObjectName(_fromUtf8("actionReception_Expedition"))
        self.menuTemperature.addAction(self.actionLaboTemp)
        self.menuTemperature.addAction(self.actionSynchronisation_enregisteurs)
        self.menuTemperature.addAction(self.actionCaracterisation_Generateurs)
        self.menuTemperature.addAction(self.actionDeclaration_incertitudes)
        self.menuTemperature.addAction(self.actionCartographie)
        self.menuTemperature.addSeparator()
        self.menuTemperature.addAction(self.actionPilotage_des_instruments)
        self.menuAfficheurs.addAction(self.actionAfficheurs)
        self.menuIntervention.addAction(self.actionAffecter)
        self.menuIntervention.addAction(self.actionModifier_2)
        self.menuIntervention.addAction(self.actionRechercher)
        self.menuInstruments.addAction(self.actionCreation)
        self.menuInstruments.addAction(self.actionModification)
        self.menuInstruments.addAction(self.menuIntervention.menuAction())
        self.menuModification.addAction(self.actionEntite_Client)
        self.menuModification.addAction(self.actionSite_Client)
        self.menuClients.addAction(self.actionCreation_2)
        self.menuClients.addAction(self.menuModification.menuAction())
        self.menuClients.addAction(self.actionRecherche_2)
        self.menuInterventions.addAction(self.actionReception_Expedition)
        self.menuInterventions.addSeparator()
        self.menuInterventions.addAction(self.actionCreer)
        self.menuInterventions.addAction(self.actionModifier)
        self.menuBase_de_Donnees.addAction(self.actionConsultation)
        self.menuAdministration.addAction(self.actionIndicateurs)
        self.menuAdministration.addAction(self.menuInstruments.menuAction())
        self.menuAdministration.addAction(self.menuBase_de_Donnees.menuAction())
        self.menuAdministration.addSeparator()
        self.menuAdministration.addAction(self.menuClients.menuAction())
        self.menuAdministration.addAction(self.menuInterventions.menuAction())
        self.menuExploitation_Certificats.addAction(self.actionPolynome)
        self.menuBar.addAction(self.menuAdministration.menuAction())
        self.menuBar.addAction(self.menuTemperature.menuAction())
        self.menuBar.addAction(self.menuAfficheurs.menuAction())
        self.menuBar.addAction(self.menuExploitation_Certificats.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Recherche", None))
        self.label.setText(_translate("MainWindow", "Valeur à chercher", None))
        self.label_2.setText(_translate("MainWindow", "Signe", None))
        self.comboBox_signe.setItemText(0, _translate("MainWindow", "Contient", None))
        self.comboBox_signe.setItemText(1, _translate("MainWindow", "=", None))
        self.comboBox_signe.setItemText(2, _translate("MainWindow", ">", None))
        self.comboBox_signe.setItemText(3, _translate("MainWindow", "<", None))
        self.comboBox_signe.setItemText(4, _translate("MainWindow", "≥", None))
        self.comboBox_signe.setItemText(5, _translate("MainWindow", "≤", None))
        self.label_3.setText(_translate("MainWindow", "Nom Colonne", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Parc d\'instrument", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Planning de receptions", None))
        self.menuTemperature.setTitle(_translate("MainWindow", "Temperature", None))
        self.menuAfficheurs.setTitle(_translate("MainWindow", "Afficheurs", None))
        self.menuAdministration.setTitle(_translate("MainWindow", "Administration", None))
        self.menuInstruments.setTitle(_translate("MainWindow", "Instruments", None))
        self.menuIntervention.setTitle(_translate("MainWindow", "Intervention", None))
        self.menuClients.setTitle(_translate("MainWindow", "Clients", None))
        self.menuModification.setTitle(_translate("MainWindow", "Modification", None))
        self.menuInterventions.setTitle(_translate("MainWindow", "Interventions", None))
        self.menuBase_de_Donnees.setTitle(_translate("MainWindow", "Base de Donnees", None))
        self.menuExploitation_Certificats.setTitle(_translate("MainWindow", "Exploitation Certificats", None))
        self.actionLaboTemp.setText(_translate("MainWindow", "LaboTemp", None))
        self.actionSynchronisation_enregisteurs.setText(_translate("MainWindow", "Synchronisation enregistreurs", None))
        self.actionCaracterisation_Generateurs.setText(_translate("MainWindow", "Caracterisation Generateurs", None))
        self.actionAfficheurs.setText(_translate("MainWindow", "Afficheurs", None))
        self.actionIndicateurs.setText(_translate("MainWindow", "Indicateurs", None))
        self.actionCreation.setText(_translate("MainWindow", "Creation(s)", None))
        self.actionModification.setText(_translate("MainWindow", "Modification(s)", None))
        self.actionRecherche.setText(_translate("MainWindow", "Recherche", None))
        self.actionCreation_2.setText(_translate("MainWindow", "Creation", None))
        self.actionRecherche_2.setText(_translate("MainWindow", "Recherche", None))
        self.actionCreer.setText(_translate("MainWindow", "Creer", None))
        self.actionModifier.setText(_translate("MainWindow", "Modifier", None))
        self.actionAffecter.setText(_translate("MainWindow", "Affecter", None))
        self.actionModifier_2.setText(_translate("MainWindow", "Modifier", None))
        self.actionRechercher.setText(_translate("MainWindow", "Rechercher", None))
        self.actionPolynome.setText(_translate("MainWindow", "Polynome", None))
        self.actionConsultation.setText(_translate("MainWindow", "Consultation", None))
        self.actionPilotage_des_instruments.setText(_translate("MainWindow", "Pilotage des instruments ", None))
        self.actionDeclaration_incertitudes.setText(_translate("MainWindow", "Declaration incertitudes", None))
        self.actionEntite_Client.setText(_translate("MainWindow", "Entite Client", None))
        self.actionSite_Client.setText(_translate("MainWindow", "Site Client", None))
        self.actionServices_Client.setText(_translate("MainWindow", "Services Client", None))
        self.actionCartographie.setText(_translate("MainWindow", "Cartographie", None))
        self.actionReception_Expedition.setText(_translate("MainWindow", "Reception_Expedition", None))

from GUI.qtableview_donnees import Tableview_donnees_fichier

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

