# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Developpement Informatique\Python\Administration\GUI\Instrument\Modification_Instruments.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Modification_Instrument(object):
    def setupUi(self, Modification_Instrument):
        Modification_Instrument.setObjectName(_fromUtf8("Modification_Instrument"))
        Modification_Instrument.resize(710, 696)
        Modification_Instrument.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Modification_Instrument.setSizeGripEnabled(True)
        self.verticalLayout_17 = QtGui.QVBoxLayout(Modification_Instrument)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_client = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_client.setObjectName(_fromUtf8("comboBox_client"))
        self.verticalLayout_2.addWidget(self.comboBox_client)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.comboBox_affectation = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_affectation.setObjectName(_fromUtf8("comboBox_affectation"))
        self.verticalLayout_8.addWidget(self.comboBox_affectation)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_11 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.comboBox_localisation = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_localisation.setObjectName(_fromUtf8("comboBox_localisation"))
        self.verticalLayout_12.addWidget(self.comboBox_localisation)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 2, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_16 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_15.addWidget(self.label_16)
        self.comboBox = QtGui.QComboBox(Modification_Instrument)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_15.addWidget(self.comboBox)
        self.gridLayout_2.addLayout(self.verticalLayout_15, 0, 3, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(Modification_Instrument)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_17.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.comboBox_designation_litt = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_designation_litt.setEnabled(True)
        self.comboBox_designation_litt.setEditable(True)
        self.comboBox_designation_litt.setObjectName(_fromUtf8("comboBox_designation_litt"))
        self.verticalLayout_7.addWidget(self.comboBox_designation_litt)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 4, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox_famille = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_famille.setObjectName(_fromUtf8("comboBox_famille"))
        self.verticalLayout_6.addWidget(self.comboBox_famille)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.comboBox_domaine_mes = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_domaine_mes.setEnabled(True)
        self.comboBox_domaine_mes.setEditable(True)
        self.comboBox_domaine_mes.setObjectName(_fromUtf8("comboBox_domaine_mes"))
        self.verticalLayout_4.addWidget(self.comboBox_domaine_mes)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_8 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.comboBox_constructeur = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_constructeur.setEditable(True)
        self.comboBox_constructeur.setObjectName(_fromUtf8("comboBox_constructeur"))
        self.verticalLayout_9.addWidget(self.comboBox_constructeur)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.comboBox_type = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_type.setEditable(True)
        self.comboBox_type.setObjectName(_fromUtf8("comboBox_type"))
        self.verticalLayout_5.addWidget(self.comboBox_type)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_9 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.comboBox_ref_constructeur = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_ref_constructeur.setEditable(True)
        self.comboBox_ref_constructeur.setObjectName(_fromUtf8("comboBox_ref_constructeur"))
        self.verticalLayout_10.addWidget(self.comboBox_ref_constructeur)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 1, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_12 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_13.addWidget(self.label_12)
        self.lineEdit_n_serie = QtGui.QLineEdit(Modification_Instrument)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_n_serie.sizePolicy().hasHeightForWidth())
        self.lineEdit_n_serie.setSizePolicy(sizePolicy)
        self.lineEdit_n_serie.setObjectName(_fromUtf8("lineEdit_n_serie"))
        self.verticalLayout_13.addWidget(self.lineEdit_n_serie)
        self.gridLayout.addLayout(self.verticalLayout_13, 2, 2, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.lineEdit_resolution = QtGui.QLineEdit(Modification_Instrument)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_resolution.sizePolicy().hasHeightForWidth())
        self.lineEdit_resolution.setSizePolicy(sizePolicy)
        self.lineEdit_resolution.setObjectName(_fromUtf8("lineEdit_resolution"))
        self.verticalLayout_11.addWidget(self.lineEdit_resolution)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 3, 1, 1)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_14 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_18.addWidget(self.label_14)
        self.comboBox_commentaire = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_commentaire.setEditable(True)
        self.comboBox_commentaire.setObjectName(_fromUtf8("comboBox_commentaire"))
        self.verticalLayout_18.addWidget(self.comboBox_commentaire)
        self.gridLayout.addLayout(self.verticalLayout_18, 2, 4, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox_designation = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_designation.setEditable(True)
        self.comboBox_designation.setObjectName(_fromUtf8("comboBox_designation"))
        self.verticalLayout_3.addWidget(self.comboBox_designation)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(Modification_Instrument)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_17.addWidget(self.line_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.checkBox_lier = QtGui.QCheckBox(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_lier.setFont(font)
        self.checkBox_lier.setObjectName(_fromUtf8("checkBox_lier"))
        self.verticalLayout_16.addWidget(self.checkBox_lier)
        self.comboBox_instrument = ExtendedCombo(Modification_Instrument)
        self.comboBox_instrument.setEnabled(False)
        self.comboBox_instrument.setObjectName(_fromUtf8("comboBox_instrument"))
        self.verticalLayout_16.addWidget(self.comboBox_instrument)
        self.gridLayout_3.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_13 = QtGui.QLabel(Modification_Instrument)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_14.addWidget(self.label_13)
        self.comboBox_etat_util = QtGui.QComboBox(Modification_Instrument)
        self.comboBox_etat_util.setObjectName(_fromUtf8("comboBox_etat_util"))
        self.comboBox_etat_util.addItem(_fromUtf8(""))
        self.comboBox_etat_util.addItem(_fromUtf8(""))
        self.comboBox_etat_util.addItem(_fromUtf8(""))
        self.verticalLayout_14.addWidget(self.comboBox_etat_util)
        self.gridLayout_3.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_3)
        self.line_3 = QtGui.QFrame(Modification_Instrument)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_17.addWidget(self.line_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_maj = QtGui.QPushButton(Modification_Instrument)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icones/icone_actualiser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_maj.setIcon(icon)
        self.pushButton_maj.setObjectName(_fromUtf8("pushButton_maj"))
        self.horizontalLayout_4.addWidget(self.pushButton_maj)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableWidget = QtGui.QTableWidget(Modification_Instrument)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Modification_Instrument)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_17.addLayout(self.verticalLayout)

        self.retranslateUi(Modification_Instrument)
        QtCore.QMetaObject.connectSlotsByName(Modification_Instrument)

    def retranslateUi(self, Modification_Instrument):
        Modification_Instrument.setWindowTitle(_translate("Modification_Instrument", "Modifiction Instrument(s)", None))
        self.label.setText(_translate("Modification_Instrument", "Client", None))
        self.label_7.setText(_translate("Modification_Instrument", "Site du Client", None))
        self.label_11.setText(_translate("Modification_Instrument", "Service d\'affectation", None))
        self.label_16.setText(_translate("Modification_Instrument", "Localisation", None))
        self.label_6.setText(_translate("Modification_Instrument", "Designation litterale", None))
        self.label_5.setText(_translate("Modification_Instrument", "Famille", None))
        self.label_3.setText(_translate("Modification_Instrument", "Domaine de Mesure", None))
        self.label_8.setText(_translate("Modification_Instrument", "Constructeur", None))
        self.label_4.setText(_translate("Modification_Instrument", "Type", None))
        self.label_9.setText(_translate("Modification_Instrument", "Reference Constructeur", None))
        self.label_12.setText(_translate("Modification_Instrument", "N° Serie", None))
        self.label_10.setText(_translate("Modification_Instrument", "Resolution", None))
        self.label_14.setText(_translate("Modification_Instrument", "Commentaire", None))
        self.label_2.setText(_translate("Modification_Instrument", "Designation", None))
        self.checkBox_lier.setText(_translate("Modification_Instrument", "Instrument à lier", None))
        self.label_13.setText(_translate("Modification_Instrument", "Etat d\'utilisation", None))
        self.comboBox_etat_util.setItemText(0, _translate("Modification_Instrument", "En Service", None))
        self.comboBox_etat_util.setItemText(1, _translate("Modification_Instrument", "En Sommeil", None))
        self.comboBox_etat_util.setItemText(2, _translate("Modification_Instrument", "Reformé", None))
        self.pushButton_maj.setText(_translate("Modification_Instrument", "Mise à jour", None))
        self.tableWidget.setSortingEnabled(True)

from GUI.Instrument.extendedcombo import ExtendedCombo
import Package.Icones_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Modification_Instrument = QtGui.QDialog()
    ui = Ui_Modification_Instrument()
    ui.setupUi(Modification_Instrument)
    Modification_Instrument.show()
    sys.exit(app.exec_())

