# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\1FC\Desktop\DEv Informatique\CARACTERISATION  MAT Température\Build\V0.1\GUI\Interface_caracterisation.ui'
#
# Created: Thu Jul 21 15:04:35 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName(_fromUtf8("Configuration"))
        Configuration.resize(1115, 814)
        self.centralWidget = QtGui.QWidget(Configuration)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton_saisie = QtGui.QRadioButton(self.groupBox)
        self.radioButton_saisie.setChecked(True)
        self.radioButton_saisie.setObjectName(_fromUtf8("radioButton_saisie"))
        self.gridLayout.addWidget(self.radioButton_saisie, 0, 0, 1, 1)
        self.radioButton_modification = QtGui.QRadioButton(self.groupBox)
        self.radioButton_modification.setObjectName(_fromUtf8("radioButton_modification"))
        self.gridLayout.addWidget(self.radioButton_modification, 0, 1, 1, 1)
        self.radioButton_consulter = QtGui.QRadioButton(self.groupBox)
        self.radioButton_consulter.setObjectName(_fromUtf8("radioButton_consulter"))
        self.gridLayout.addWidget(self.radioButton_consulter, 0, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEdit)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox_operateur = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_operateur.setObjectName(_fromUtf8("comboBox_operateur"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_operateur)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox_type_caract = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_type_caract.setObjectName(_fromUtf8("comboBox_type_caract"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_type_caract)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_generateur = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_generateur.setObjectName(_fromUtf8("comboBox_generateur"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_generateur)
        self.lineEdit_huile = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_huile.setObjectName(_fromUtf8("lineEdit_huile"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_huile)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_Pb = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Pb.setObjectName(_fromUtf8("lineEdit_Pb"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_Pb)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.textEdit_commentaire = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_commentaire.sizePolicy().hasHeightForWidth())
        self.textEdit_commentaire.setSizePolicy(sizePolicy)
        self.textEdit_commentaire.setObjectName(_fromUtf8("textEdit_commentaire"))
        self.verticalLayout.addWidget(self.textEdit_commentaire)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.Filtres = QtGui.QWidget(self.splitter)
        self.Filtres.setObjectName(_fromUtf8("Filtres"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Filtres)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_3 = QtGui.QCheckBox(self.Filtres)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_4.addWidget(self.checkBox_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(self.Filtres)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.comboBox_type_caract_2 = QtGui.QComboBox(self.Filtres)
        self.comboBox_type_caract_2.setEnabled(False)
        self.comboBox_type_caract_2.setObjectName(_fromUtf8("comboBox_type_caract_2"))
        self.horizontalLayout_2.addWidget(self.comboBox_type_caract_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.Filtres)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.Filtres)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.dateEdit_2 = QtGui.QDateEdit(self.Filtres)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout.addWidget(self.dateEdit_2)
        self.comboBox_2 = QtGui.QComboBox(self.Filtres)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_2 = QtGui.QCheckBox(self.Filtres)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.Filtres)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.comboBox_etat_carac = QtGui.QComboBox(self.Filtres)
        self.comboBox_etat_carac.setEnabled(False)
        self.comboBox_etat_carac.setObjectName(_fromUtf8("comboBox_etat_carac"))
        self.comboBox_etat_carac.addItem(_fromUtf8(""))
        self.comboBox_etat_carac.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_etat_carac)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_4 = QtGui.QCheckBox(self.Filtres)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.Filtres)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.comboBox_generateur_2 = QtGui.QComboBox(self.Filtres)
        self.comboBox_generateur_2.setEnabled(False)
        self.comboBox_generateur_2.setObjectName(_fromUtf8("comboBox_generateur_2"))
        self.horizontalLayout_3.addWidget(self.comboBox_generateur_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.Filtres)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.tableWidget_recap = QtGui.QTableWidget(self.splitter)
        self.tableWidget_recap.setObjectName(_fromUtf8("tableWidget_recap"))
        self.tableWidget_recap.setColumnCount(6)
        self.tableWidget_recap.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_recap.setHorizontalHeaderItem(5, item)
        self.verticalLayout_7.addWidget(self.splitter)
        Configuration.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Configuration)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuEnregistrement = QtGui.QMenu(self.menuBar)
        self.menuEnregistrement.setObjectName(_fromUtf8("menuEnregistrement"))
        self.menuGraphique = QtGui.QMenu(self.menuBar)
        self.menuGraphique.setObjectName(_fromUtf8("menuGraphique"))
        Configuration.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuEnregistrement.menuAction())
        self.menuBar.addAction(self.menuGraphique.menuAction())

        self.retranslateUi(Configuration)
        QtCore.QObject.connect(self.radioButton_saisie, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Filtres.hide)
        QtCore.QObject.connect(self.radioButton_modification, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Filtres.show)
        QtCore.QObject.connect(self.radioButton_consulter, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Filtres.show)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        Configuration.setWindowTitle(_translate("Configuration", "MainWindow", None))
        self.groupBox.setTitle(_translate("Configuration", "Selectionner Action", None))
        self.radioButton_saisie.setText(_translate("Configuration", "Saisir", None))
        self.radioButton_modification.setText(_translate("Configuration", "Modifier", None))
        self.radioButton_consulter.setText(_translate("Configuration", "Consulter", None))
        self.label.setText(_translate("Configuration", "Date", None))
        self.label_3.setText(_translate("Configuration", "Responsable Caracterisation", None))
        self.label_4.setText(_translate("Configuration", "Type de caracterisation", None))
        self.label_6.setText(_translate("Configuration", "Huile", None))
        self.label_2.setText(_translate("Configuration", "Generateur", None))
        self.label_7.setText(_translate("Configuration", "Pb", None))
        self.label_5.setText(_translate("Configuration", "Commentaires : ", None))
        self.checkBox_3.setText(_translate("Configuration", "CheckBox", None))
        self.label_11.setText(_translate("Configuration", "Type de caracterisation", None))
        self.checkBox.setText(_translate("Configuration", "CheckBox", None))
        self.label_9.setText(_translate("Configuration", "Date", None))
        self.comboBox_2.setItemText(0, _translate("Configuration", "=", None))
        self.comboBox_2.setItemText(1, _translate("Configuration", "<", None))
        self.comboBox_2.setItemText(2, _translate("Configuration", ">", None))
        self.comboBox_2.setItemText(3, _translate("Configuration", "<=", None))
        self.comboBox_2.setItemText(4, _translate("Configuration", ">=", None))
        self.checkBox_2.setText(_translate("Configuration", "CheckBox", None))
        self.label_8.setText(_translate("Configuration", "Etat", None))
        self.comboBox_etat_carac.setItemText(0, _translate("Configuration", "Actif", None))
        self.comboBox_etat_carac.setItemText(1, _translate("Configuration", "Archivé", None))
        self.checkBox_4.setText(_translate("Configuration", "CheckBox", None))
        self.label_10.setText(_translate("Configuration", "Generateur", None))
        self.label_12.setText(_translate("Configuration", "Filtres", None))
        item = self.tableWidget_recap.horizontalHeaderItem(0)
        item.setText(_translate("Configuration", "Date Caracterisation", None))
        item = self.tableWidget_recap.horizontalHeaderItem(1)
        item.setText(_translate("Configuration", "Generateur", None))
        item = self.tableWidget_recap.horizontalHeaderItem(2)
        item.setText(_translate("Configuration", "Operateur", None))
        item = self.tableWidget_recap.horizontalHeaderItem(3)
        item.setText(_translate("Configuration", "Type de Caracterisation", None))
        item = self.tableWidget_recap.horizontalHeaderItem(4)
        item.setText(_translate("Configuration", "Commentaire", None))
        item = self.tableWidget_recap.horizontalHeaderItem(5)
        item.setText(_translate("Configuration", "Etat de la carcaterisation", None))
        self.menuEnregistrement.setTitle(_translate("Configuration", "Enregistrement", None))
        self.menuGraphique.setTitle(_translate("Configuration", "Graphique", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Configuration = QtGui.QMainWindow()
    ui = Ui_Configuration()
    ui.setupUi(Configuration)
    Configuration.show()
    sys.exit(app.exec_())

