# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Developpement Informatique\Python\Administration\Modules\Cartographie\GUI\Main_Carto.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Cartographie(object):
    def setupUi(self, Cartographie):
        Cartographie.setObjectName(_fromUtf8("Cartographie"))
        Cartographie.resize(800, 600)
        self.centralWidget = QtGui.QWidget(Cartographie)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("QLabel{\n"
"background-color: rgb(170, 255, 255);\n"
"border: 1px solid Black;\n"
"border-radius: 5px;}"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.tableWidget_recap = TableWidget_Recap(self.centralWidget)
        self.tableWidget_recap.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_recap.setFont(font)
        self.tableWidget_recap.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_recap.setMouseTracking(True)
        self.tableWidget_recap.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableWidget_recap.setWhatsThis(_fromUtf8(""))
        self.tableWidget_recap.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_recap.setAlternatingRowColors(True)
        self.tableWidget_recap.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_recap.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget_recap.setShowGrid(True)
        self.tableWidget_recap.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_recap.setWordWrap(True)
        self.tableWidget_recap.setCornerButtonEnabled(True)
        self.tableWidget_recap.setRowCount(0)
        self.tableWidget_recap.setObjectName(_fromUtf8("tableWidget_recap"))
        self.tableWidget_recap.setColumnCount(13)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_recap.setHorizontalHeaderItem(12, item)
        self.tableWidget_recap.horizontalHeader().setVisible(True)
        self.tableWidget_recap.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_recap.horizontalHeader().setHighlightSections(True)
        self.tableWidget_recap.verticalHeader().setVisible(True)
        self.tableWidget_recap.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout.addWidget(self.tableWidget_recap)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        Cartographie.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Cartographie)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuNouvelle_Cartographie = QtGui.QMenu(self.menuBar)
        self.menuNouvelle_Cartographie.setObjectName(_fromUtf8("menuNouvelle_Cartographie"))
        Cartographie.setMenuBar(self.menuBar)
        self.actionNouvelle_Cartographie = QtGui.QAction(Cartographie)
        self.actionNouvelle_Cartographie.setObjectName(_fromUtf8("actionNouvelle_Cartographie"))
        self.actionModifier_une_cartographie = QtGui.QAction(Cartographie)
        self.actionModifier_une_cartographie.setObjectName(_fromUtf8("actionModifier_une_cartographie"))
        self.actionAnnule_et_Remplace = QtGui.QAction(Cartographie)
        self.actionAnnule_et_Remplace.setObjectName(_fromUtf8("actionAnnule_et_Remplace"))
        self.menuNouvelle_Cartographie.addAction(self.actionNouvelle_Cartographie)
        self.menuNouvelle_Cartographie.addAction(self.actionModifier_une_cartographie)
        self.menuNouvelle_Cartographie.addAction(self.actionAnnule_et_Remplace)
        self.menuBar.addAction(self.menuNouvelle_Cartographie.menuAction())

        self.retranslateUi(Cartographie)
        QtCore.QMetaObject.connectSlotsByName(Cartographie)

    def retranslateUi(self, Cartographie):
        Cartographie.setWindowTitle(_translate("Cartographie", "Cartographie v 0.3", None))
        self.label_7.setText(_translate("Cartographie", "Recapitulatif des Cartographies", None))
        self.tableWidget_recap.setSortingEnabled(True)
        item = self.tableWidget_recap.horizontalHeaderItem(0)
        item.setText(_translate("Cartographie", "Enceinte", None))
        item = self.tableWidget_recap.horizontalHeaderItem(1)
        item.setText(_translate("Cartographie", "Date", None))
        item = self.tableWidget_recap.horizontalHeaderItem(2)
        item.setText(_translate("Cartographie", "Nom", None))
        item = self.tableWidget_recap.horizontalHeaderItem(3)
        item.setText(_translate("Cartographie", "Prenom", None))
        item = self.tableWidget_recap.horizontalHeaderItem(4)
        item.setText(_translate("Cartographie", "Rapport", None))
        item = self.tableWidget_recap.horizontalHeaderItem(5)
        item.setText(_translate("Cartographie", "Centrale", None))
        item = self.tableWidget_recap.horizontalHeaderItem(6)
        item.setText(_translate("Cartographie", "Application", None))
        item = self.tableWidget_recap.horizontalHeaderItem(7)
        item.setText(_translate("Cartographie", "Condition Desiree", None))
        item = self.tableWidget_recap.horizontalHeaderItem(8)
        item.setText(_translate("Cartographie", "Temp Consigne", None))
        item = self.tableWidget_recap.horizontalHeaderItem(9)
        item.setText(_translate("Cartographie", "Signe EMT", None))
        item = self.tableWidget_recap.horizontalHeaderItem(10)
        item.setText(_translate("Cartographie", "EMT", None))
        item = self.tableWidget_recap.horizontalHeaderItem(11)
        item.setText(_translate("Cartographie", "Nouvelle colonne", None))
        item = self.tableWidget_recap.horizontalHeaderItem(12)
        item.setText(_translate("Cartographie", "Conformite", None))
        self.menuNouvelle_Cartographie.setTitle(_translate("Cartographie", "Menu", None))
        self.actionNouvelle_Cartographie.setText(_translate("Cartographie", "Nouvelle Cartographie", None))
        self.actionModifier_une_cartographie.setText(_translate("Cartographie", "Modifier une Cartographie", None))
        self.actionAnnule_et_Remplace.setText(_translate("Cartographie", "Annule et Remplace", None))

from Modules.Cartographie.GUI.Tablewidget_Recap import TableWidget_Recap

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Cartographie = QtGui.QMainWindow()
    ui = Ui_Cartographie()
    ui.setupUi(Cartographie)
    Cartographie.show()
    sys.exit(app.exec_())

