# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\Logiciels\Logiciels_techniques_labo\0_ A valider tester\Caracterisation\V1.1\GUI\Caracterisation_enceinte\Interface_modification_caracterisation_enceinte.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Modification_caracterisation_enceinte(object):
    def setupUi(self, Modification_caracterisation_enceinte):
        Modification_caracterisation_enceinte.setObjectName(_fromUtf8("Modification_caracterisation_enceinte"))
        Modification_caracterisation_enceinte.resize(959, 927)
        self.centralWidget = QtGui.QWidget(Modification_caracterisation_enceinte)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 99))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setContentsMargins(-1, 13, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_2.addWidget(self.dateEdit, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_operateur = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_operateur.setFont(font)
        self.comboBox_operateur.setObjectName(_fromUtf8("comboBox_operateur"))
        self.gridLayout_2.addWidget(self.comboBox_operateur, 1, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox.setReadOnly(True)
        self.spinBox.setMinimum(1)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.lineEdit_id_caracterisation = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_id_caracterisation.setFont(font)
        self.lineEdit_id_caracterisation.setReadOnly(True)
        self.lineEdit_id_caracterisation.setObjectName(_fromUtf8("lineEdit_id_caracterisation"))
        self.gridLayout_2.addWidget(self.lineEdit_id_caracterisation, 3, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 127))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setContentsMargins(-1, 13, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_enceinte = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_enceinte.setFont(font)
        self.comboBox_enceinte.setObjectName(_fromUtf8("comboBox_enceinte"))
        self.horizontalLayout.addWidget(self.comboBox_enceinte)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(103, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_marque = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_marque.setFont(font)
        self.lineEdit_marque.setReadOnly(True)
        self.lineEdit_marque.setObjectName(_fromUtf8("lineEdit_marque"))
        self.horizontalLayout_2.addWidget(self.lineEdit_marque)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_n_serie = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_n_serie.setFont(font)
        self.lineEdit_n_serie.setReadOnly(True)
        self.lineEdit_n_serie.setObjectName(_fromUtf8("lineEdit_n_serie"))
        self.horizontalLayout_3.addWidget(self.lineEdit_n_serie)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(84, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_model = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_model.setFont(font)
        self.lineEdit_model.setReadOnly(True)
        self.lineEdit_model.setObjectName(_fromUtf8("lineEdit_model"))
        self.horizontalLayout_4.addWidget(self.lineEdit_model)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 63))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_11.setContentsMargins(-1, 13, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_etalon = QtGui.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_etalon.setFont(font)
        self.comboBox_etalon.setObjectName(_fromUtf8("comboBox_etalon"))
        self.horizontalLayout_6.addWidget(self.comboBox_etalon)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_centrale = QtGui.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_centrale.setFont(font)
        self.comboBox_centrale.setObjectName(_fromUtf8("comboBox_centrale"))
        self.horizontalLayout_7.addWidget(self.comboBox_centrale)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setContentsMargins(-1, 13, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter_2 = QtGui.QSplitter(self.tab_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.comboBox_polynome_etalon = QtGui.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_polynome_etalon.setFont(font)
        self.comboBox_polynome_etalon.setObjectName(_fromUtf8("comboBox_polynome_etalon"))
        self.verticalLayout_5.addWidget(self.comboBox_polynome_etalon)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.lineEdit_ax2 = QtGui.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_ax2.setFont(font)
        self.lineEdit_ax2.setReadOnly(True)
        self.lineEdit_ax2.setObjectName(_fromUtf8("lineEdit_ax2"))
        self.verticalLayout_7.addWidget(self.lineEdit_ax2)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_8.addWidget(self.label_18)
        self.lineEdit_bx = QtGui.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_bx.setFont(font)
        self.lineEdit_bx.setReadOnly(True)
        self.lineEdit_bx.setObjectName(_fromUtf8("lineEdit_bx"))
        self.verticalLayout_8.addWidget(self.lineEdit_bx)
        self.horizontalLayout_19.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_9.addWidget(self.label_19)
        self.lineEdit_c = QtGui.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_c.setFont(font)
        self.lineEdit_c.setReadOnly(True)
        self.lineEdit_c.setObjectName(_fromUtf8("lineEdit_c"))
        self.verticalLayout_9.addWidget(self.lineEdit_c)
        self.horizontalLayout_19.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.tableWidget_u_etalon = QtGui.QTableWidget(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_u_etalon.setFont(font)
        self.tableWidget_u_etalon.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_u_etalon.setCornerButtonEnabled(True)
        self.tableWidget_u_etalon.setObjectName(_fromUtf8("tableWidget_u_etalon"))
        self.tableWidget_u_etalon.setColumnCount(4)
        self.tableWidget_u_etalon.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_etalon.setItem(5, 0, item)
        self.tableWidget_u_etalon.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_5.addWidget(self.tableWidget_u_etalon)
        self.groupBox_6 = QtGui.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.groupBox_6)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableWidget_select_sondes = Tablewidget_select_sondes_centrales(self.splitter)
        self.tableWidget_select_sondes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_select_sondes.setObjectName(_fromUtf8("tableWidget_select_sondes"))
        self.tableWidget_select_sondes.setColumnCount(2)
        self.tableWidget_select_sondes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_select_sondes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_select_sondes.setHorizontalHeaderItem(1, item)
        self.textEdit_list_ce_centrale = QtGui.QTextEdit(self.splitter)
        self.textEdit_list_ce_centrale.setObjectName(_fromUtf8("textEdit_list_ce_centrale"))
        self.tableWidget_u_centrale = QtGui.QTableWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_u_centrale.setFont(font)
        self.tableWidget_u_centrale.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_u_centrale.setCornerButtonEnabled(True)
        self.tableWidget_u_centrale.setObjectName(_fromUtf8("tableWidget_u_centrale"))
        self.tableWidget_u_centrale.setColumnCount(4)
        self.tableWidget_u_centrale.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_u_centrale.setHorizontalHeaderItem(3, item)
        self.tableWidget_u_centrale.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.lineEdit_u_moyens_mesure = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_u_moyens_mesure.setStyleSheet(_fromUtf8(""))
        self.lineEdit_u_moyens_mesure.setReadOnly(True)
        self.lineEdit_u_moyens_mesure.setObjectName(_fromUtf8("lineEdit_u_moyens_mesure"))
        self.horizontalLayout_16.addWidget(self.lineEdit_u_moyens_mesure)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(15)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_21.addWidget(self.label_22)
        self.lineEdit_u_moyens = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_u_moyens.setStyleSheet(_fromUtf8(""))
        self.lineEdit_u_moyens.setReadOnly(True)
        self.lineEdit_u_moyens.setObjectName(_fromUtf8("lineEdit_u_moyens"))
        self.horizontalLayout_21.addWidget(self.lineEdit_u_moyens)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.lineEdit_temperature = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_temperature.sizePolicy().hasHeightForWidth())
        self.lineEdit_temperature.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_temperature.setFont(font)
        self.lineEdit_temperature.setText(_fromUtf8(""))
        self.lineEdit_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temperature.setObjectName(_fromUtf8("lineEdit_temperature"))
        self.verticalLayout_2.addWidget(self.lineEdit_temperature)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tableWidget_mesures = QtGui.QTableWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_mesures.sizePolicy().hasHeightForWidth())
        self.tableWidget_mesures.setSizePolicy(sizePolicy)
        self.tableWidget_mesures.setMinimumSize(QtCore.QSize(870, 537))
        self.tableWidget_mesures.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tableWidget_mesures.setDragDropOverwriteMode(False)
        self.tableWidget_mesures.setAlternatingRowColors(True)
        self.tableWidget_mesures.setShowGrid(True)
        self.tableWidget_mesures.setObjectName(_fromUtf8("tableWidget_mesures"))
        self.tableWidget_mesures.setColumnCount(8)
        self.tableWidget_mesures.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_mesures.setHorizontalHeaderItem(7, item)
        self.tableWidget_mesures.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget_mesures.verticalHeader().setMinimumSectionSize(45)
        self.verticalLayout_3.addWidget(self.tableWidget_mesures)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(113, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_stab_max = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_stab_max.setFont(font)
        self.lineEdit_stab_max.setReadOnly(True)
        self.lineEdit_stab_max.setObjectName(_fromUtf8("lineEdit_stab_max"))
        self.horizontalLayout_12.addWidget(self.lineEdit_stab_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(31)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_20.addWidget(self.label_21)
        self.lineEdit_ecarttype_max = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_ecarttype_max.setObjectName(_fromUtf8("lineEdit_ecarttype_max"))
        self.horizontalLayout_20.addWidget(self.lineEdit_ecarttype_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(113, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.lineEdit_hom_max_2 = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_hom_max_2.setFont(font)
        self.lineEdit_hom_max_2.setReadOnly(True)
        self.lineEdit_hom_max_2.setObjectName(_fromUtf8("lineEdit_hom_max_2"))
        self.horizontalLayout_13.addWidget(self.lineEdit_hom_max_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(113, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.lineEdit_u_stab_max = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_u_stab_max.setFont(font)
        self.lineEdit_u_stab_max.setReadOnly(True)
        self.lineEdit_u_stab_max.setObjectName(_fromUtf8("lineEdit_u_stab_max"))
        self.horizontalLayout_14.addWidget(self.lineEdit_u_stab_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.lineEdit_u_hom_max = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_u_hom_max.setFont(font)
        self.lineEdit_u_hom_max.setReadOnly(True)
        self.lineEdit_u_hom_max.setObjectName(_fromUtf8("lineEdit_u_hom_max"))
        self.horizontalLayout_15.addWidget(self.lineEdit_u_hom_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.pushButton_precedent = QtGui.QPushButton(self.tab_2)
        self.pushButton_precedent.setObjectName(_fromUtf8("pushButton_precedent"))
        self.horizontalLayout_17.addWidget(self.pushButton_precedent)
        self.pushButton_suivant = QtGui.QPushButton(self.tab_2)
        self.pushButton_suivant.setObjectName(_fromUtf8("pushButton_suivant"))
        self.horizontalLayout_17.addWidget(self.pushButton_suivant)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_pt = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pt.sizePolicy().hasHeightForWidth())
        self.label_pt.setSizePolicy(sizePolicy)
        self.label_pt.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_pt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pt.setObjectName(_fromUtf8("label_pt"))
        self.horizontalLayout_18.addWidget(self.label_pt)
        self.label_16 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_18.addWidget(self.label_16)
        self.label_nb_pt = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nb_pt.sizePolicy().hasHeightForWidth())
        self.label_nb_pt.setSizePolicy(sizePolicy)
        self.label_nb_pt.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_nb_pt.setObjectName(_fromUtf8("label_nb_pt"))
        self.horizontalLayout_18.addWidget(self.label_nb_pt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        Modification_caracterisation_enceinte.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Modification_caracterisation_enceinte)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 959, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuEnregistrer = QtGui.QMenu(self.menuBar)
        self.menuEnregistrer.setObjectName(_fromUtf8("menuEnregistrer"))
        Modification_caracterisation_enceinte.setMenuBar(self.menuBar)
        self.actionSauvegarder = QtGui.QAction(Modification_caracterisation_enceinte)
        self.actionSauvegarder.setObjectName(_fromUtf8("actionSauvegarder"))
        self.menuEnregistrer.addAction(self.actionSauvegarder)
        self.menuBar.addAction(self.menuEnregistrer.menuAction())

        self.retranslateUi(Modification_caracterisation_enceinte)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_nb_pt.setNum)
        QtCore.QMetaObject.connectSlotsByName(Modification_caracterisation_enceinte)

    def retranslateUi(self, Modification_caracterisation_enceinte):
        Modification_caracterisation_enceinte.setWindowTitle(_translate("Modification_caracterisation_enceinte", "Modification_Caracterisation Enceinte", None))
        self.groupBox_2.setTitle(_translate("Modification_caracterisation_enceinte", "Renseignements", None))
        self.label_5.setText(_translate("Modification_caracterisation_enceinte", "Responsable mesures", None))
        self.label_9.setText(_translate("Modification_caracterisation_enceinte", "Nbr de Temperature", None))
        self.label_20.setText(_translate("Modification_caracterisation_enceinte", "ID Caracterisation", None))
        self.groupBox.setTitle(_translate("Modification_caracterisation_enceinte", "Enceinte", None))
        self.label.setText(_translate("Modification_caracterisation_enceinte", "Nom Enceinte", None))
        self.label_2.setText(_translate("Modification_caracterisation_enceinte", "Marque", None))
        self.label_3.setText(_translate("Modification_caracterisation_enceinte", "N° de Serie", None))
        self.label_4.setText(_translate("Modification_caracterisation_enceinte", "Model", None))
        self.groupBox_3.setTitle(_translate("Modification_caracterisation_enceinte", "Moyens", None))
        self.label_6.setText(_translate("Modification_caracterisation_enceinte", "Etalon", None))
        self.label_7.setText(_translate("Modification_caracterisation_enceinte", "Centrale", None))
        self.groupBox_4.setTitle(_translate("Modification_caracterisation_enceinte", "Charge / Commentaires", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Modification_caracterisation_enceinte", "Configuration", None))
        self.groupBox_5.setTitle(_translate("Modification_caracterisation_enceinte", "Etalon", None))
        self.label_15.setText(_translate("Modification_caracterisation_enceinte", "Polynome:", None))
        self.label_17.setText(_translate("Modification_caracterisation_enceinte", "ax²", None))
        self.label_18.setText(_translate("Modification_caracterisation_enceinte", "bx", None))
        self.label_19.setText(_translate("Modification_caracterisation_enceinte", "c", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Etalonnage", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Polynome", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "Resolution", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "Derive", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(4)
        item.setText(_translate("Modification_caracterisation_enceinte", "Autoechauffement", None))
        item = self.tableWidget_u_etalon.verticalHeaderItem(5)
        item.setText(_translate("Modification_caracterisation_enceinte", "Temp.Ambiante", None))
        item = self.tableWidget_u_etalon.horizontalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Valeur", None))
        item = self.tableWidget_u_etalon.horizontalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Distribution", None))
        item = self.tableWidget_u_etalon.horizontalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "u(xi)", None))
        item = self.tableWidget_u_etalon.horizontalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "u(xi)²", None))
        __sortingEnabled = self.tableWidget_u_etalon.isSortingEnabled()
        self.tableWidget_u_etalon.setSortingEnabled(False)
        item = self.tableWidget_u_etalon.item(2, 0)
        item.setText(_translate("Modification_caracterisation_enceinte", "0.001", None))
        item = self.tableWidget_u_etalon.item(4, 0)
        item.setText(_translate("Modification_caracterisation_enceinte", "0.007", None))
        item = self.tableWidget_u_etalon.item(5, 0)
        item.setText(_translate("Modification_caracterisation_enceinte", "0.006", None))
        self.tableWidget_u_etalon.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(_translate("Modification_caracterisation_enceinte", "Sondes_centrale", None))
        item = self.tableWidget_select_sondes.horizontalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Nom_sonde", None))
        item = self.tableWidget_select_sondes.horizontalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Utilisée", None))
        item = self.tableWidget_u_centrale.verticalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Etalonnage", None))
        item = self.tableWidget_u_centrale.verticalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Modelisation", None))
        item = self.tableWidget_u_centrale.verticalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "Resolution", None))
        item = self.tableWidget_u_centrale.verticalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "Derive", None))
        item = self.tableWidget_u_centrale.horizontalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Valeur", None))
        item = self.tableWidget_u_centrale.horizontalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Distribution", None))
        item = self.tableWidget_u_centrale.horizontalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "u(xi)", None))
        item = self.tableWidget_u_centrale.horizontalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "u(xi)²", None))
        self.label_14.setText(_translate("Modification_caracterisation_enceinte", "Somme u(xi)²", None))
        self.label_22.setText(_translate("Modification_caracterisation_enceinte", "u moyens utilisés", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Modification_caracterisation_enceinte", "Moyens de mesure", None))
        self.label_8.setText(_translate("Modification_caracterisation_enceinte", "Temperature :", None))
        item = self.tableWidget_mesures.verticalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "CENTRE", None))
        item = self.tableWidget_mesures.verticalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "HAD", None))
        item = self.tableWidget_mesures.verticalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "HAG", None))
        item = self.tableWidget_mesures.verticalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "HPD", None))
        item = self.tableWidget_mesures.verticalHeaderItem(4)
        item.setText(_translate("Modification_caracterisation_enceinte", "HPG", None))
        item = self.tableWidget_mesures.verticalHeaderItem(5)
        item.setText(_translate("Modification_caracterisation_enceinte", "BAD", None))
        item = self.tableWidget_mesures.verticalHeaderItem(6)
        item.setText(_translate("Modification_caracterisation_enceinte", "BAG", None))
        item = self.tableWidget_mesures.verticalHeaderItem(7)
        item.setText(_translate("Modification_caracterisation_enceinte", "BPD", None))
        item = self.tableWidget_mesures.verticalHeaderItem(8)
        item.setText(_translate("Modification_caracterisation_enceinte", "BPG", None))
        item = self.tableWidget_mesures.verticalHeaderItem(9)
        item.setText(_translate("Modification_caracterisation_enceinte", "ETALON", None))
        item = self.tableWidget_mesures.verticalHeaderItem(10)
        item.setText(_translate("Modification_caracterisation_enceinte", "ETALON \n"
"Corrigé", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(0)
        item.setText(_translate("Modification_caracterisation_enceinte", "Minimum", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(1)
        item.setText(_translate("Modification_caracterisation_enceinte", "Maximum", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(2)
        item.setText(_translate("Modification_caracterisation_enceinte", "Moyenne", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(3)
        item.setText(_translate("Modification_caracterisation_enceinte", "Ecart type", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(4)
        item.setText(_translate("Modification_caracterisation_enceinte", "Stabilité", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(5)
        item.setText(_translate("Modification_caracterisation_enceinte", "ε\n"
"(REF-Sonde)", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(6)
        item.setText(_translate("Modification_caracterisation_enceinte", "u\n"
"moyens_utilisés", None))
        item = self.tableWidget_mesures.horizontalHeaderItem(7)
        item.setText(_translate("Modification_caracterisation_enceinte", "u\n"
"homogénéité", None))
        self.label_10.setText(_translate("Modification_caracterisation_enceinte", "Stabilité max", None))
        self.label_21.setText(_translate("Modification_caracterisation_enceinte", "Ecart Type max", None))
        self.label_11.setText(_translate("Modification_caracterisation_enceinte", "Homogeneité max", None))
        self.label_12.setText(_translate("Modification_caracterisation_enceinte", "u stabilite max", None))
        self.label_13.setText(_translate("Modification_caracterisation_enceinte", "u homogeneite max", None))
        self.pushButton_precedent.setText(_translate("Modification_caracterisation_enceinte", "Precedent", None))
        self.pushButton_suivant.setText(_translate("Modification_caracterisation_enceinte", "Suivant", None))
        self.label_pt.setText(_translate("Modification_caracterisation_enceinte", "TextLabel", None))
        self.label_16.setText(_translate("Modification_caracterisation_enceinte", "/", None))
        self.label_nb_pt.setText(_translate("Modification_caracterisation_enceinte", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Modification_caracterisation_enceinte", "Mesures", None))
        self.menuEnregistrer.setTitle(_translate("Modification_caracterisation_enceinte", "Enregistrer", None))
        self.actionSauvegarder.setText(_translate("Modification_caracterisation_enceinte", "Mise à jour", None))

from Modules.Caracterisation_generateurs_temperature.GUI.Caracterisation_enceinte.Tablewidget_select_sondes_centrales import Tablewidget_select_sondes_centrales

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Modification_caracterisation_enceinte = QtGui.QMainWindow()
    ui = Ui_Modification_caracterisation_enceinte()
    ui.setupUi(Modification_caracterisation_enceinte)
    Modification_caracterisation_enceinte.show()
    sys.exit(app.exec_())

